# Generated by Django 5.1.4 on 2024-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolregistration",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="schoolregistration",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="schoolregistration",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="schoolregistration",
            name="pincode",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="schoolregistration",
            name="school_website",
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="schoolregistration",
            name="state",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="schoolregistration",
            name="surname",
            field=models.CharField(max_length=255),
        ),
    ]
